### ISSUE TITLE
'' is an incorrect path for a scene file. BuildPlayer expects paths relative to the project folder.

### ISSUE THREAD

**Issue by Troshchuk** [google/play-instant-unity-plugin#26]
When I try build instant app with button "Build for play console" I have error: " '' is an incorrect path for a scene file. BuildPlayer expects paths relative to the project folder. " Override Scenes (Optional) is empty. Could you investigate this issue? Thanks

**Comment by thanwah** [comment]
Hi, thanks for filing this issue.

If you've been using release v0.7 of the plugin, my suspicion is that this may be an issue fixed by pull #20. I just released v0.8 of the plugin that includes the fixes from #20.

Do you mind trying [release v0.8](https://github.com/google/play-instant-unity-plugin/releases/tag/v0.8) to see if that fixes your issue?

Another possibility is that there is an issue with the selected scenes from Unity's Build Settings window. Do you mind sharing your Unity version as well as a screen shot of this window so I can see if anything looks unusual?

Thanks again.

**Comment by Troshchuk** [comment]
Hi,

I tried v0.8 but the issue was not fixed. 

I use Unity 2018.2.2f1 on Mac OS. Here you are screenshot: https://pasteboard.co/Hzi4lX4.png

Thanks.

**Comment by thanwah** [comment]
Thanks for sharing your Unity version.

I apologize, but I was not clear when I requested a screenshot. What I had intended to request was the Build Settings windows. Is it possible for you to share a screenshot of those?

For example:
<img width="1100" alt="screen shot 2018-08-15 at 4 25 18 pm" src="https://user-images.githubusercontent.com/38674020/44171476-4fe29780-a0a8-11e8-9e04-7c4d5013189f.png">

**Comment by Troshchuk** [comment]
Here you are:
<img width="1270" alt="screen shot 2018-08-16 at 1 05 44 am" src="https://user-images.githubusercontent.com/5609510/44175946-9d82f280-a0f0-11e8-9f9c-6040ed058ce1.png">

**Comment by towicode** [comment]
I just wanted to say I ran into this issue today with a fresh attempt to install. I am on OSX

**Comment by 960208781** [comment]
Check your "BuildPipeline.BuildPlayer" function, I caused by incorrect because levels of parameters

**Comment by Esmolan** [comment]
Hey!

I had this same problem. I realized that in my case with **Jenkins**, the **EditorBuildSettings** do not save like in your screenshot in wherever else you have the project opened. They get deleted.

So what I did is, I first let Jenkins clone the project. Then I open it in a Unity Editor (whatever version you project lives in) and then I add the scenes I want to build to the **Build Settings**. Then I run Jenkins again and it finally finds the scenes to build.

Hope that helps!
